const data = [
  {
    id: 1,
    name: "Banana Crème Pie Pop-Tarts",
    nutrition: {
      servSize: "2 Pastries (96g)",
      calories: 380,
      fat: {
        totalFat: "10g",
        saturatedFat: "3g",
        transFat: "0g",
        polyUnsaturatedFat: "3.5g",
        monoUnsaturatedFat: "2.5g",
      },
      cholesterol: "0mg",
      sodium: "340mg",
      carbs: {
        totalCarbs: "69g",
        dietaryFiber: "1g",
        totalSugars: "28g",
        addedSugars: "27g",
      },
      protein: "4g",
      supplements: {
        vitaminD: "0mcg",
        calcium: "0mg",
        iron: "1.4mg",
        potassium: "40mg",
        thiamin: "",
        riboflavin: "",
        niacin: "",
        folate: "40mcg",
      },
    },
  },
  {
    id: 2,
    name: "Cinnamon Sugar Pretzel Pop-Tarts",
    nutrition: {
      servSize: "2 Pastries (96g)",
      calories: 390,
      fat: {
        totalFat: "13g",
        saturatedFat: "4.5g",
        transFat: "0g",
        polyUnsaturatedFat: "5g",
        monoUnsaturatedFat: "3g",
      },
      cholesterol: "0mg",
      sodium: "560mg",
      carbs: {
        totalCarbs: "65g",
        dietaryFiber: "1g",
        totalSugars: "27g",
        addedSugars: "27g",
      },
      protein: "4g",
      supplements: {
        vitaminD: "0mcg",
        calcium: "10mg",
        iron: "1.5mg",
        potassium: "50mg",
        thiamin: "",
        riboflavin: "",
        niacin: "",
        folate: "40mcg",
      },
    },
  },
  {
    id: 3,
    name: "Eggo Frosted Maple Flavor Pop-Tarts",
    nutrition: {
      servSize: "2 Pastries (96g)",
      calories: 380,
      fat: {
        totalFat: "12g",
        saturatedFat: "3.5g",
        transFat: "0g",
        polyUnsaturatedFat: "4.5g",
        monoUnsaturatedFat: "2.5g",
      },
      cholesterol: "0mg",
      sodium: "330mg",
      carbs: {
        totalCarbs: "67g",
        dietaryFiber: "1g",
        totalSugars: "30g",
        addedSugars: "30g",
      },
      protein: "4g",
      supplements: {
        vitaminD: "0mcg",
        calcium: "10mg",
        iron: "1.4mg",
        potassium: "50mg",
        thiamin: "",
        riboflavin: "",
        niacin: "",
        folate: "40mcg",
      },
    },
  },
  {
    id: 4,
    name: "Froot Loops Pop-Tarts",
    nutrition: {
      servSize: "2 Pastries (96g)",
      calories: 370,
      fat: {
        totalFat: "9g",
        saturatedFat: "3g",
        transFat: "0g",
        polyUnsaturatedFat: "3.5g",
        monoUnsaturatedFat: "2g",
      },
      cholesterol: "0mg",
      sodium: "320mg",
      carbs: {
        totalCarbs: "70g",
        dietaryFiber: "1g",
        totalSugars: "30g",
        addedSugars: "30g",
      },
      protein: "4g",
      supplements: {
        vitaminD: "0mcg",
        calcium: "0mg",
        iron: "1.5mg",
        potassium: "40mg",
        thiamin: "",
        riboflavin: "",
        niacin: "",
        folate: "40mcg",
      },
    },
  },
  {
    id: 5,
    name: "Frosted Apple Fritter Pop-Tarts",
    nutrition: {
      servSize: "2 Pastries (96g)",
      calories: 370,
      fat: {
        totalFat: "9g",
        saturatedFat: "3g",
        transFat: "0g",
        polyUnsaturatedFat: "3.5g",
        monoUnsaturatedFat: "2g",
      },
      cholesterol: "0mg",
      sodium: "260mg",
      carbs: {
        totalCarbs: "69g",
        dietaryFiber: "1g",
        totalSugars: "29g",
        addedSugars: "28g",
      },
      protein: "4g",
      supplements: {
        vitaminD: "0mcg",
        calcium: "10mg",
        iron: "1.4mg",
        potassium: "60mg",
        thiamin: "",
        riboflavin: "",
        niacin: "",
        folate: "40mcg",
      },
    },
  },
  {
    id: 6,
    name: "Frosted Blueberry Pop-Tarts",
    nutrition: {
      servSize: "2 Pastry (96g)",
      calories: 370,
      fat: {
        totalFat: "9g",
        saturatedFat: "3g",
        transFat: "0g",
        polyUnsaturatedFat: "3.5g",
        monoUnsaturatedFat: "2g",
      },
      cholesterol: "0mg",
      sodium: "320mg",
      carbs: {
        totalCarbs: "70g",
        dietaryFiber: "1g",
        totalSugars: "30g",
        addedSugars: "29g",
      },
      protein: "3g",
      supplements: {
        vitaminD: "0mcg",
        calcium: "10mg",
        iron: "1.5mg",
        potassium: "50mg",
        thiamin: "",
        riboflavin: "",
        niacin: "",
        folate: "40mcg",
      },
    },
  },
  {
    id: 7,
    name: "Frosted Boston Creme Donut Pop-Tarts",
    nutrition: {
      servSize: "2 Pastries (96g)",
      calories: 370,
      fat: {
        totalFat: "9g",
        saturatedFat: "3g",
        transFat: "0g",
        polyUnsaturatedFat: "3g",
        monoUnsaturatedFat: "2g",
      },
      cholesterol: "0mg",
      sodium: "250mg",
      carbs: {
        totalCarbs: "70g",
        dietaryFiber: "1g",
        totalSugars: "31g",
        addedSugars: "30g",
      },
      protein: "4g",
      supplements: {
        vitaminD: "0mcg",
        calcium: "90mg",
        iron: "1.4mg",
        potassium: "70mg",
        thiamin: "",
        riboflavin: "",
        niacin: "",
        folate: "40mcg",
      },
    },
  },
  {
    id: 8,
    name: "Frosted Brown Sugar Cinnamon Pop-Tarts",
    nutrition: {
      servSize: "2 Pastries (96g)",
      calories: 400,
      fat: {
        totalFat: "13g",
        saturatedFat: "4.5g",
        transFat: "0g",
        polyUnsaturatedFat: "5g",
        monoUnsaturatedFat: "3g",
      },
      cholesterol: "0mg",
      sodium: "340mg",
      carbs: {
        totalCarbs: "68g",
        dietaryFiber: "1g",
        totalSugars: "30g",
        addedSugars: "29g",
      },
      protein: "4g",
      supplements: {
        vitaminD: "0mcg",
        calcium: "10mg",
        iron: "1.5mg",
        potassium: "70mg",
        thiamin: "",
        riboflavin: "",
        niacin: "",
        folate: "40mcg",
      },
    },
  },
  {
    id: 9,
    name: "Frosted Cherry Pop-Tarts",
    nutrition: {
      servSize: "2 Pastries (96g)",
      calories: 370,
      fat: {
        totalFat: "9g",
        saturatedFat: "3g",
        transFat: "0g",
        polyUnsaturatedFat: "3.5g",
        monoUnsaturatedFat: "2g",
      },
      cholesterol: "0mg",
      sodium: "320mg",
      carbs: {
        totalCarbs: "70g",
        dietaryFiber: "1g",
        totalSugars: "30g",
        addedSugars: "30g",
      },
      protein: "3g",
      supplements: {
        vitaminD: "0mcg",
        calcium: "0mg",
        iron: "1.5mg",
        potassium: "40mg",
        thiamin: "",
        riboflavin: "",
        niacin: "",
        folate: "40mg",
      },
    },
  },
  {
    id: 10,
    name: "Frosted Chocolate Chip Pop-Tarts",
    nutrition: {
      servSize: "1 Pastry (52g)",
      calories: 210,
      caloriesFromFat: 50,
      fat: {
        totalFat: "6g",
        saturatedFat: "2g",
        transFat: "0g",
        polyUnsaturatedFat: "2g",
        monoUnsaturatedFat: "1.5g",
      },
      cholesterol: "0mg",
      sodium: "240mg",
      carbs: {
        totalCarbs: "36g",
        dietaryFiber: "<1g",
        totalSugars: "18g",
        addedSugars: "",
      },
      protein: "2g",
      supplements: {
        vitaminD: "",
        calcium: "",
        iron: "",
        potassium: "",
        thiamin: "",
        riboflavin: "",
        niacin: "",
        folate: "",
      },
    },
  },
  {
    id: 11,
    name: "Frosted Chocolate Chip Cookie Dough Pop Tarts",
    nutrition: {
      servSize: "1 Pastry (50g)",
      calories: 190,
      caloriesFromFat: 45,
      fat: {
        totalFat: "5g",
        saturatedFat: "2g",
        transFat: "0g",
        polyUnsaturatedFat: "1.5g",
        monoUnsaturatedFat: "1g",
      },
      cholesterol: "0mg",
      sodium: "190mg",
      carbs: {
        totalCarbs: "35g",
        dietaryFiber: "<1g",
        totalSugars: "18g",
        addedSugars: "2g",
      },
      protein: "2g",
      supplements: {
        vitaminD: "",
        calcium: "",
        iron: "",
        potassium: "",
        thiamin: "",
        riboflavin: "",
        niacin: "",
        folate: "",
      },
    },
  },
  {
    id: 12,
    name: "Frosted Chocolate Fudge Pop-Tarts",
    nutrition: {
      servSize: "1 Pastry (52g)",
      calories: 200,
      caloriesFromFat: 45,
      fat: {
        totalFat: "4.5g",
        saturatedFat: "1.5g",
        transFat: "0g",
        polyUnsaturatedFat: "1.5g",
        monoUnsaturatedFat: "1g",
      },
      cholesterol: "0mg",
      sodium: "220mg",
      carbs: {
        totalCarbs: "37g",
        dietaryFiber: "1g",
        totalSugars: "19g",
        addedSugars: "",
      },
      protein: "2g",
      supplements: {
        vitaminD: "",
        calcium: "",
        iron: "",
        potassium: "",
        thiamin: "",
        riboflavin: "",
        niacin: "",
        folate: "",
      },
    },
  },
  {
    id: 13,
    name: "Frosted Chocolatey Churro Pop-Tarts",
    nutrition: {
      servSize: "2 Pastries (96g)",
      calories: 400,
      fat: {
        totalFat: "13g",
        saturatedFat: "4.5g",
        transFat: "0g",
        polyUnsaturatedFat: "5g",
        monoUnsaturatedFat: "3g",
      },
      cholesterol: "0mg",
      sodium: "330mg",
      carbs: {
        totalCarbs: "68g",
        dietaryFiber: "1g",
        totalSugars: "31g",
        addedSugars: "31g",
      },
      protein: "4g",
      supplements: {
        vitaminD: "0mcg",
        calcium: "10mg",
        iron: "1.5mg",
        potassium: "50mg",
        thiamin: "",
        riboflavin: "",
        niacin: "",
        folate: "40mcg",
      },
    },
  },
  {
    id: 14,
    name: "Frosted Cinnamon Roll Pop-Tarts",
    nutrition: {
      servSize: "1 Pastry (50g)",
      calories: 210,
      caloriesFromFat: 60,
      fat: {
        totalFat: "7g",
        saturatedFat: "2.5g",
        transFat: "0g",
        polyUnsaturatedFat: "2.5g",
        monoUnsaturatedFat: "1.5g",
      },
      cholesterol: "0mg",
      sodium: "170mg",
      carbs: {
        totalCarbs: "34g",
        dietaryFiber: "<1g",
        totalSugars: "13g",
        addedSugars: "",
      },
      protein: "2g",
      supplements: {
        vitaminD: "",
        calcium: "",
        iron: "",
        potassium: "",
        thiamin: "",
        riboflavin: "",
        niacin: "",
        folate: "",
      },
    },
  },
  {
    id: 15,
    name: "Frosted Confetti Cupcake Pop-Tarts",
    nutrition: {
      servSize: "2 Pastries (96g)",
      calories: 360,
      fat: {
        totalFat: "7g",
        saturatedFat: "2.5g",
        transFat: "0g",
        polyUnsaturatedFat: "2.5g",
        monoUnsaturatedFat: "1.5g",
      },
      cholesterol: "0mg",
      sodium: "440mg",
      carbs: {
        totalCarbs: "70g",
        dietaryFiber: "1g",
        totalSugars: "30g",
        addedSugars: "30g",
      },
      protein: "4g",
      supplements: {
        vitaminD: "0mcg",
        calcium: "0mg",
        iron: "1.5mg",
        potassium: "40mg",
        thiamin: "",
        riboflavin: "",
        niacin: "",
        folate: "40mcg",
      },
    },
  },
  {
    id: 16,
    name: "Frosted Cookies & Crème Pop-Tarts",
    nutrition: {
      servSize: "2 Pastries (96g)",
      calories: 360,
      fat: {
        totalFat: "9g",
        saturatedFat: "3.5g",
        transFat: "0g",
        polyUnsaturatedFat: "3.5g",
        monoUnsaturatedFat: "2g",
      },
      cholesterol: "0mg",
      sodium: "470mg",
      carbs: {
        totalCarbs: "67g",
        dietaryFiber: "2g",
        totalSugars: "38g",
        addedSugars: "36g",
      },
      protein: "4g",
      supplements: {
        vitaminD: "0mcg",
        calcium: "20mg",
        iron: "1.5mg",
        potassium: "420mg",
        thiamin: "",
        riboflavin: "",
        niacin: "",
        folate: "40mcg",
      },
    },
  },
  {
    id: 17,
    name: "Frosted Hot Fudge Sundae Pop-Tarts",
    nutrition: {
      servSize: "2 Pastries (96g)",
      calories: 370,
      fat: {
        totalFat: "9g",
        saturatedFat: "3g",
        transFat: "0g",
        polyUnsaturatedFat: "3g",
        monoUnsaturatedFat: "2g",
      },
      cholesterol: "0mg",
      sodium: "430mg",
      carbs: {
        totalCarbs: "70g",
        dietaryFiber: "1g",
        totalSugars: "33g",
        addedSugars: "32g",
      },
      protein: "4g",
      supplements: {
        vitaminD: "0mcg",
        calcium: "10mg",
        iron: "1.5mg",
        potassium: "140mg",
        thiamin: "",
        riboflavin: "",
        niacin: "",
        folate: "40mg",
      },
    },
  },
  {
    id: 18,
    name: "Frosted Raspberry Pop-Tarts",
    nutrition: {
      servSize: "2 Pastries (96g)",
      calories: 370,
      fat: {
        totalFat: "9g",
        saturatedFat: "3g",
        transFat: "0g",
        polyUnsaturatedFat: "3.5g",
        monoUnsaturatedFat: "2g",
      },
      cholesterol: "0mg",
      sodium: "320mg",
      carbs: {
        totalCarbs: "70g",
        dietaryFiber: "1g",
        totalSugars: "30g",
        addedSugars: "30g",
      },
      protein: "3g",
      supplements: {
        vitaminD: "0mcg",
        calcium: "0mg",
        iron: "1.5mg",
        potassium: "40mg",
        thiamin: "",
        riboflavin: "",
        niacin: "",
        folate: "40mcg",
      },
    },
  },
  {
    id: 19,
    name: "Frosted S'Mores Pop-Tarts",
    nutrition: {
      servSize: "2 Pastries (96g)",
      calories: 370,
      fat: {
        totalFat: "9g",
        saturatedFat: "3g",
        transFat: "0g",
        polyUnsaturatedFat: "3.5g",
        monoUnsaturatedFat: "2g",
      },
      cholesterol: "0mg",
      sodium: "390mg",
      carbs: {
        totalCarbs: "67g",
        dietaryFiber: "1g",
        totalSugars: "35g",
        addedSugars: "33g",
      },
      protein: "5g",
      supplements: {
        vitaminD: "0mcg",
        calcium: "30mg",
        iron: "1.5mg",
        potassium: "150mg",
        thiamin: "",
        riboflavin: "",
        niacin: "",
        folate: "40mcg",
      },
    },
  },
  {
    id: 20,
    name: "Frosted Strawberry Pop-Tarts",
    nutrition: {
      servSize: "2 Pastries (96g)",
      calories: 370,
      fat: {
        totalFat: "9g",
        saturatedFat: "3g",
        transFat: "0g",
        polyUnsaturatedFat: "3.5g",
        monoUnsaturatedFat: "2g",
      },
      cholesterol: "0mg",
      sodium: "320mg",
      carbs: {
        totalCarbs: "70g",
        dietaryFiber: "1g",
        totalSugars: "30g",
        addedSugars: "30g",
      },
      protein: "3g",
      supplements: {
        vitaminD: "0mcg",
        calcium: "10mg",
        iron: "1.5mg",
        potassium: "50mg",
        thiamin: "",
        riboflavin: "",
        niacin: "",
        folate: "40mcg",
      },
    },
  },
  {
    id: 21,
    name: "Frosted Wildlicious Wild Berry Pop",
    nutrition: {
      servSize: "2 Pastries (96g)",
      calories: 370,
      fat: {
        totalFat: "9g",
        saturatedFat: "3g",
        transFat: "0g",
        polyUnsaturatedFat: "3.5g",
        monoUnsaturatedFat: "2g",
      },
      cholesterol: "0mg",
      sodium: "320mg",
      carbs: {
        totalCarbs: "70g",
        dietaryFiber: "1g",
        totalSugars: "31g",
        addedSugars: "31g",
      },
      protein: "3g",
      supplements: {
        vitaminD: "0mcg",
        calcium: "10mg",
        iron: "1.5mg",
        potassium: "50mg",
        thiamin: "",
        riboflavin: "",
        niacin: "",
        folate: "40mcg",
      },
    },
  },
  {
    id: 22,
    name: "Lemon Crème Pie Pop-Tarts",
    nutrition: {
      servSize: "2 Pastries (96g)",
      calories: 380,
      fat: {
        totalFat: "10g",
        saturatedFat: "3g",
        transFat: "0g",
        polyUnsaturatedFat: "3.5g",
        monoUnsaturatedFat: "2.5g",
      },
      cholesterol: "0mg",
      sodium: "340mg",
      carbs: {
        totalCarbs: "69g",
        dietaryFiber: "1g",
        totalSugars: "28g",
        addedSugars: "27g",
      },
      protein: "4g",
      supplements: {
        vitaminD: "0mcg",
        calcium: "0mg",
        iron: "1.4mg",
        potassium: "40mg",
        thiamin: "",
        riboflavin: "",
        niacin: "",
        folate: "40mcg",
      },
    },
  },
  {
    id: 23,
    name: "Salted Caramel Pretzel Pop-Tarts",
    nutrition: {
      servSize: "2 Pastries (96g)",
      calories: 380,
      fat: {
        totalFat: "12g",
        saturatedFat: "4g",
        transFat: "0g",
        polyUnsaturatedFat: "4g",
        monoUnsaturatedFat: "2.5g",
      },
      cholesterol: "0mg",
      sodium: "710mg",
      carbs: {
        totalCarbs: "66g",
        dietaryFiber: "1g",
        totalSugars: "23g",
        addedSugars: "23g",
      },
      protein: "4g",
      supplements: {
        vitaminD: "0mcg",
        calcium: "10mg",
        iron: "1.4g",
        potassium: "50mg",
        thiamin: "",
        riboflavin: "",
        niacin: "",
        folate: "40mcg",
      },
    },
  },
  {
    id: 24,
    name: "Simply Frosted Harvest Strawberry Pop-Tarts",
    nutrition: {
      servSize: "2 Pastries (96g)",
      calories: 380,
      fat: {
        totalFat: "10g",
        saturatedFat: "5g",
        transFat: "0g",
        polyUnsaturatedFat: "1g",
        monoUnsaturatedFat: "3.5g",
      },
      cholesterol: "0mg",
      sodium: "340mg",
      carbs: {
        totalCarbs: "70g",
        dietaryFiber: "1g",
        totalSugars: "28g",
        addedSugars: "28g",
      },
      protein: "4g",
      supplements: {
        vitaminD: "0mcg",
        calcium: "0mg",
        iron: "1.5mg",
        potassium: "50mg",
        thiamin: "",
        riboflavin: "",
        niacin: "",
        folate: "40mcg",
      },
    },
  },
  {
    id: 25,
    name: "Unfrosted Blueberry Pop-Tarts",
    nutrition: {
      servSize: "2 Pastries (96g)",
      calories: 380,
      fat: {
        totalFat: "10g",
        saturatedFat: "3g",
        transFat: "0g",
        polyUnsaturatedFat: "3.5g",
        monoUnsaturatedFat: "2g",
      },
      cholesterol: "0mg",
      sodium: "360mg",
      carbs: {
        totalCarbs: "69g",
        dietaryFiber: "1g",
        totalSugars: "24g",
        addedSugars: "24g",
      },
      protein: "4g",
      supplements: {
        vitaminD: "0mcg",
        calcium: "0mg",
        iron: "1.4mg",
        potassium: "40mg",
        thiamin: "",
        riboflavin: "",
        niacin: "",
        folate: "40mcg",
      },
    },
  },
  {
    id: 26,
    name: "Unfrosted Brown Sugar Cinnamon Pop-Tarts",
    nutrition: {
      servSize: "2 Pastries (96g)",
      calories: 410,
      fat: {
        totalFat: "15g",
        saturatedFat: "5g",
        transFat: "0g",
        polyUnsaturatedFat: "6g",
        monoUnsaturatedFat: "3.5g",
      },
      cholesterol: "0mg",
      sodium: "380g",
      carbs: {
        totalCarbs: "66g",
        dietaryFiber: "2g",
        totalSugars: "24g",
        addedSugars: "24g",
      },
      protein: "5g",
      supplements: {
        vitaminD: "0mcg",
        calcium: "10mg",
        iron: "1.5mg",
        potassium: "60mg",
        thiamin: "",
        riboflavin: "",
        niacin: "",
        folate: "40mcg",
      },
    },
  },
  {
    id: 27,
    name: "Unfrosted Strawberry Pop-Tarts",
    nutrition: {
      servSize: "2 Pastries (96g)",
      calories: 380,
      fat: {
        totalFat: "10g",
        saturatedFat: "3g",
        transFat: "0g",
        polyUnsaturatedFat: "3.5g",
        monoUnsaturatedFat: "2g",
      },
      cholesterol: "0mg",
      sodium: "360mg",
      carbs: {
        totalCarbs: "69g",
        dietaryFiber: "1g",
        totalSugars: "25g",
        addedSugars: "24g",
      },
      protein: "4g",
      supplements: {
        vitaminD: "0mcg",
        calcium: "0mg",
        iron: "1.4mg",
        potassium: "40mg",
        thiamin: "",
        riboflavin: "",
        niacin: "",
        folate: "20mcg",
      },
    },
  },
];

module.exports = { data };
